export const mockFields = [
    {
        id: 1,
        field_name: "Sân Bóng Chảo Lửa",
        branch_name: "Cơ sở Tân Bình",
        field_thumb:
            "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "30 Phan Thúc Duyện, Phường 4, Tân Bình, TP.HCM",
        field_types: ["Sân 5", "Sân 7"],
        price_per_hour: 250000,
        grass_type: "Cỏ nhân tạo",
        rating: 4.5,
        slug: "abc",
    },
    {
        id: 2,
        field_name: "Sân Vận Động K34",
        branch_name: "Quận 10",
        field_thumb:
            "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "A75/6B/35 Bạch Đằng, Phường 2, Tân Bình, TP.HCM",
        field_types: ["Sân 5", "Sân 7", "Sân 11"],
        price_per_hour: 300000,
        grass_type: "Cỏ tự nhiên",
        rating: 5.0,
        slug: "abc",
    },
    {
        id: 3,
        field_name: "Sân Cầu Lông & Đá Bóng",
        branch_name: "Thủ Đức",
        field_thumb:
            "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "Đường số 10, Linh Chiểu, Thủ Đức, TP.HCM",
        field_types: ["Sân 5"],
        price_per_hour: 180000,
        grass_type: "Cỏ nhân tạo",
        rating: 3.5,
        slug: "abc",
    },
    {
        id: 4,
        field_name: "Sân Bóng Thành Long",
        branch_name: "Bình Chánh",
        field_thumb:
            "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "B8/251 Quốc lộ 50, Xã Phong Phú, Bình Chánh",
        field_types: ["Sân 7", "Sân 11"],
        price_per_hour: 500000,
        grass_type: "Cỏ lai",
        rating: 4.0,
        slug: "abc",
    },
    {
        id: 3,
        field_name: "Sân Cầu Lông & Đá Bóng",
        branch_name: "Thủ Đức",
        field_thumb:
            "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "Đường số 10, Linh Chiểu, Thủ Đức, TP.HCM",
        field_types: ["Sân 5"],
        price_per_hour: 180000,
        grass_type: "Cỏ nhân tạo",
        rating: 3.5,
        slug: "abc",
    },
    {
        id: 4,
        field_name: "Sân Bóng Thành Long",
        branch_name: "Bình Chánh",
        field_thumb:
            "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "B8/251 Quốc lộ 50, Xã Phong Phú, Bình Chánh",
        field_types: ["Sân 7", "Sân 11"],
        price_per_hour: 500000,
        grass_type: "Cỏ lai",
        rating: 4.0,
        slug: "abc",
    },
    {
        id: 3,
        field_name: "Sân Cầu Lông & Đá Bóng",
        branch_name: "Thủ Đức",
        field_thumb:
            "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "Đường số 10, Linh Chiểu, Thủ Đức, TP.HCM",
        field_types: ["Sân 5"],
        price_per_hour: 180000,
        grass_type: "Cỏ nhân tạo",
        rating: 3.5,
        slug: "abc",
    },
    {
        id: 4,
        field_name: "Sân Bóng Thành Long",
        branch_name: "Bình Chánh",
        field_thumb:
            "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "B8/251 Quốc lộ 50, Xã Phong Phú, Bình Chánh",
        field_types: ["Sân 7", "Sân 11"],
        price_per_hour: 500000,
        grass_type: "Cỏ lai",
        rating: 4.0,
        slug: "abc",
    },
    {
        id: 3,
        field_name: "Sân Cầu Lông & Đá Bóng",
        branch_name: "Thủ Đức",
        field_thumb:
            "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "Đường số 10, Linh Chiểu, Thủ Đức, TP.HCM",
        field_types: ["Sân 5"],
        price_per_hour: 180000,
        grass_type: "Cỏ nhân tạo",
        rating: 3.5,
        slug: "abc",
    },
    {
        id: 4,
        field_name: "Sân Bóng Thành Long",
        branch_name: "Bình Chánh",
        field_thumb:
            "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        address: "B8/251 Quốc lộ 50, Xã Phong Phú, Bình Chánh",
        field_types: ["Sân 7", "Sân 11"],
        price_per_hour: 500000,
        grass_type: "Cỏ lai",
        rating: 4.0,
        slug: "abc",
    },
];
